language: node_js
os: linux
dist: xenial
node_js:
- '14'
branches:
  only:
  - main
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - npm run test
  - npm run coveralls